import { useCallback, useEffect, useState } from 'react'
import { apiFetch as fetch, apiUrl } from './api-client'
import './tourism.css'

const keyStore = 'chaurpati-admin-key'
type Category = { id: string; slug: string; nameNp: string; nameEn: string; icon?: string | null; isActive?: boolean }
type Place = { id: string; nameNp: string; nameEn?: string | null; slug: string; tourismStatus: string; wardNumber?: number | null; latitude?: number | null; longitude?: number | null; viewCount: number; averageRating: number; ratingCount: number; category?: Category; tourismImages?: { id: string; url: string; isFeatured: boolean }[] }
type Field = { key: string; np: string; en: string }
const fields: Field[] = [
  { key: 'shortDescription', np: 'छोटो विवरण', en: 'Short description' }, { key: 'description', np: 'विस्तृत विवरण', en: 'Description' },
  { key: 'history', np: 'इतिहास', en: 'History' }, { key: 'culturalSignificance', np: 'सांस्कृतिक महत्व', en: 'Cultural significance' },
  { key: 'religiousSignificance', np: 'धार्मिक महत्व', en: 'Religious significance' }, { key: 'naturalFeatures', np: 'प्राकृतिक विशेषता', en: 'Natural features' },
  { key: 'activities', np: 'गतिविधिहरू', en: 'Things to do' }, { key: 'bestTime', np: 'भ्रमणका लागि उपयुक्त समय', en: 'Best time to visit' },
  { key: 'howToReach', np: 'कसरी पुग्ने?', en: 'How to reach' }, { key: 'facilities', np: 'उपलब्ध सुविधा', en: 'Facilities' },
  { key: 'safetyInfo', np: 'सुरक्षा जानकारी', en: 'Safety information' }, { key: 'emergencyInfo', np: 'आपत्कालीन जानकारी', en: 'Emergency information' },
]
const blank = (): Record<string, string> => ({ nameNp: '', nameEn: '', slug: '', categoryId: '', wardNumber: '', latitude: '', longitude: '', address: '', sourceName: '', sourceUrl: '', ...Object.fromEntries(fields.flatMap((field) => [[`${field.key}Np`, ''], [`${field.key}En`, '']])) })
export function AdminTourismView() {
  const [key, setKey] = useState(() => sessionStorage.getItem(keyStore) || ''); const [draftKey, setDraftKey] = useState(''); const [categories, setCategories] = useState<Category[]>([]); const [places, setPlaces] = useState<Place[]>([]); const [reviews, setReviews] = useState<{ id: string; content: string; status: string; place: { nameNp: string } }[]>([]); const [reports, setReports] = useState<{ id: string; reason: string; details?: string | null; status: string; review: { content: string; place: { nameNp: string } } }[]>([]); const [dashboard, setDashboard] = useState<Record<string, number>>({}); const [form, setForm] = useState<Record<string, string>>(blank()); const [editing, setEditing] = useState(''); const [images, setImages] = useState<{ id: string; url: string; isFeatured: boolean }[]>([]); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [tab, setTab] = useState<'places' | 'categories' | 'reviews' | 'reports'>('places'); const [catNameNp, setCatNameNp] = useState(''); const [catNameEn, setCatNameEn] = useState('')
  const call = useCallback(async <T,>(url: string, init?: RequestInit): Promise<T> => { const response = await fetch(url, { ...init, headers: { Authorization: `Bearer ${key}`, ...(init?.headers || {}) } }); if (!response.ok) { const result = await response.json().catch(() => ({})) as { message?: string }; if (response.status === 401) { sessionStorage.removeItem(keyStore); setKey('') }; throw new Error(result.message || `Request failed (${response.status})`) } return response.json() as Promise<T> }, [key])
  const reload = useCallback(async () => { if (!key) return; setError(''); try { const [cats, rows, stats, reviewRows, reportRows] = await Promise.all([call<Category[]>('/api/v1/tourism/admin/categories'), call<Place[]>('/api/v1/tourism/admin/places'), call<Record<string, number>>('/api/v1/tourism/admin/dashboard'), call<typeof reviews>('/api/v1/tourism/admin/reviews'), call<typeof reports>('/api/v1/tourism/admin/review-reports')]); setCategories(cats); setPlaces(rows); setDashboard(stats); setReviews(reviewRows); setReports(reportRows) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load tourism management') } }, [call, key])
  useEffect(() => { void reload() }, [reload])
  const auth = (event: React.FormEvent) => { event.preventDefault(); sessionStorage.setItem(keyStore, draftKey); setKey(draftKey) }
  if (!key) return <main className="tourism-admin-page"><form className="tourism-admin-login" onSubmit={auth}><a href="/">← Chaurpati portal</a><span className="section-kicker">ADMINISTRATION</span><h1>Tourism management</h1><p>Enter the ADMIN_API_KEY configured in backend/.env. It is stored in this browser tab only.</p><label>Admin API key<input type="password" autoComplete="current-password" value={draftKey} onChange={(e) => setDraftKey(e.target.value)} required /></label><button>Continue</button>{error && <p role="alert">{error}</p>}</form></main>
  const update = (name: string, value: string) => setForm((old) => ({ ...old, [name]: value }))
  const edit = (place: Place & Record<string, unknown>) => { setEditing(place.id); setImages(place.tourismImages || []); const next = blank(); for (const name of Object.keys(next)) next[name] = place[name] == null ? '' : String(place[name]); next.categoryId = place.category?.id || ''; next.wardNumber = place.wardNumber == null ? '' : String(place.wardNumber); next.latitude = place.latitude == null ? '' : String(place.latitude); next.longitude = place.longitude == null ? '' : String(place.longitude); setForm(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const body = { ...form, wardNumber: form.wardNumber || null, latitude: form.latitude || null, longitude: form.longitude || null }; const place = await call<Place>(editing ? `/api/v1/tourism/admin/places/${editing}` : '/api/v1/tourism/admin/places', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setEditing(place.id); setStatus('Draft saved. Add photos, source details, then verify and publish.'); await reload() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save place') } finally { setBusy(false) } }
  const upload = async (files: File[]) => {
    if (!files.length || !editing) return
    if (files.length + images.length > 5) { setError(`You can add up to 5 photos. ${images.length} already uploaded.`); return }
    setBusy(true); setError(''); setStatus('')
    let uploaded = images
    try {
      for (const file of files) {
        const data = new FormData(); data.append('file', file)
        const result = await call<{ url: string }>('/api/v1/tourism/admin/upload', { method: 'POST', body: data })
        const image = await call<{ id: string; url: string; isFeatured: boolean }>(`/api/v1/tourism/admin/places/${editing}/images`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: result.url, altText: form.nameNp, isFeatured: uploaded.length === 0 }) })
        uploaded = [...uploaded, image]
        setImages(uploaded)
      }
      setStatus(`${files.length} photo${files.length === 1 ? '' : 's'} uploaded.`)
      await reload()
    } catch (e) { setError(e instanceof Error ? e.message : 'Upload failed') } finally { setBusy(false) }
  }
  const act = async (id: string, action: string) => { setError(''); try { await call(`/api/v1/tourism/admin/places/${id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action }) }); setStatus(`Place ${action}d.`); await reload() } catch (e) { setError(e instanceof Error ? e.message : 'Action failed') } }
  return <main className="tourism-admin-page"><header className="tourism-admin-header"><a href="/">← Chaurpati portal</a><div><span className="section-kicker">ADMINISTRATION</span><h1>Tourism management</h1></div><button onClick={() => { sessionStorage.removeItem(keyStore); setKey('') }}>Sign out</button></header>
    <section className="tourism-admin-stats">{[['All places', dashboard.total], ['Published', dashboard.published], ['Drafts', dashboard.drafts], ['Views', dashboard.views], ['Pending reviews', dashboard.reviewsPending]].map(([label, value]) => <article key={String(label)}><strong>{Number(value || 0).toLocaleString()}</strong><span>{label}</span></article>)}</section>
    <nav className="tourism-admin-tabs">{(['places', 'categories', 'reviews', 'reports'] as const).map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav>
    {error && <p className="tourism-admin-error" role="alert">{error}</p>}{status && <p className="tourism-admin-status" role="status">{status}</p>}
    {tab === 'places' && <div className="tourism-admin-layout"><form className="tourism-admin-form" onSubmit={save}><h2>{editing ? 'Edit tourism place' : 'Add tourism place'}</h2><label>Nepali name (required)<input required maxLength={160} value={form.nameNp} onChange={(e) => update('nameNp', e.target.value)} /></label><label>English name<input value={form.nameEn} onChange={(e) => update('nameEn', e.target.value)} /></label><label>Public URL slug<input value={form.slug} onChange={(e) => update('slug', e.target.value)} placeholder="auto-generated from name" /></label><div className="tourism-admin-row"><label>Category<select value={form.categoryId} onChange={(e) => update('categoryId', e.target.value)}><option value="">No category</option>{categories.filter((category) => category.id).map((category) => <option key={category.id} value={category.id} disabled={category.isActive === false}>{category.nameNp} · {category.nameEn}</option>)}</select></label><label>Ward<select value={form.wardNumber} onChange={(e) => update('wardNumber', e.target.value)}><option value="">Unknown</option>{Array.from({ length: 7 }, (_, i) => <option key={i} value={i + 1}>{i + 1}</option>)}</select></label></div><h3>Coordinates</h3><p className="tourism-admin-hint">Latitude and longitude are optional. Add both if you want this place to appear as a pin on the map.</p><div className="tourism-admin-row"><label>Latitude<input type="number" step="any" value={form.latitude} onChange={(e) => update('latitude', e.target.value)} /></label><label>Longitude<input type="number" step="any" value={form.longitude} onChange={(e) => update('longitude', e.target.value)} /></label></div><label>Address<input value={form.address} onChange={(e) => update('address', e.target.value)} /></label>
      <h3>Official source (required to verify)</h3><label>Source name<input value={form.sourceName} onChange={(e) => update('sourceName', e.target.value)} /></label><label>Source URL<input type="url" value={form.sourceUrl} onChange={(e) => update('sourceUrl', e.target.value)} /></label>
      {fields.map((field) => <fieldset key={field.key}><legend>{field.np} / {field.en}</legend><label>{field.np}<textarea rows={3} value={form[`${field.key}Np`] || ''} onChange={(e) => update(`${field.key}Np`, e.target.value)} /></label><label>{field.en}<textarea rows={3} value={form[`${field.key}En`] || ''} onChange={(e) => update(`${field.key}En`, e.target.value)} /></label></fieldset>)}
      <section className="tourism-admin-photos"><h3>Photo gallery (optional)</h3><label>Choose up to 5 JPG, PNG, or WEBP photos (max 5 MB each)<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(e) => { void upload(Array.from(e.target.files || [])); e.currentTarget.value = '' }} disabled={!editing || busy || images.length >= 5} /></label><div>{images.map((image) => <img key={image.id} src={apiUrl(image.url)} alt="Tourism place" loading="lazy" />)}</div><small>{editing ? `${images.length} of 5 photos uploaded. Photos are optional.` : 'Save the draft first to upload optional photos.'}</small></section>
      <button disabled={busy}>{busy ? 'Saving…' : 'Save draft'}</button>{editing && <button type="button" className="tourism-admin-secondary" onClick={() => { setEditing(''); setImages([]); setForm(blank()) }}>New place</button>}</form>
      <section className="tourism-admin-list"><h2>Tourism places</h2>{places.map((place) => <article key={place.id}><div><strong>{place.nameNp}</strong><small>{place.nameEn} · {place.tourismStatus} · {place.viewCount} views · ★ {Number(place.averageRating).toFixed(1)}</small></div><button onClick={() => edit(place as Place & Record<string, unknown>)}>Edit</button><div className="tourism-admin-actions">{place.tourismStatus === 'DRAFT' && <button onClick={() => void act(place.id, 'verify')}>Verify</button>}{place.tourismStatus === 'VERIFIED' && <button onClick={() => void act(place.id, 'publish')}>Publish</button>}{place.tourismStatus === 'PUBLISHED' && <button onClick={() => void act(place.id, 'unpublish')}>Unpublish</button>}<button onClick={() => void act(place.id, 'archive')}>Archive</button></div></article>)}</section></div>}
    {tab === 'categories' && <section className="tourism-admin-categories"><h2>Tourism categories</h2><form onSubmit={async (e) => { e.preventDefault(); try { await call('/api/v1/tourism/admin/categories', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nameNp: catNameNp, nameEn: catNameEn }) }); setCatNameNp(''); setCatNameEn(''); await reload() } catch (err) { setError(err instanceof Error ? err.message : 'Could not add category') } }}><input placeholder="नेपाली नाम" value={catNameNp} onChange={(e) => setCatNameNp(e.target.value)} required /><input placeholder="English name" value={catNameEn} onChange={(e) => setCatNameEn(e.target.value)} required /><button>Add category</button></form>{categories.map((category) => <article className="tourism-category-admin-row" key={category.id}><span>{category.icon} {category.nameNp} · {category.nameEn} {category.isActive === false ? '(inactive)' : ''}</span><button onClick={async () => { const nameNp = window.prompt('Nepali category name', category.nameNp); if (nameNp === null) return; const nameEn = window.prompt('English category name', category.nameEn); if (nameEn === null) return; try { await call(`/api/v1/tourism/admin/categories/${category.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nameNp, nameEn, isActive: category.isActive !== false }) }); await reload() } catch (err) { setError(err instanceof Error ? err.message : 'Could not update category') } }}>Edit</button><button onClick={async () => { try { await call(`/api/v1/tourism/admin/categories/${category.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nameNp: category.nameNp, nameEn: category.nameEn, isActive: category.isActive === false }) }); await reload() } catch (err) { setError(err instanceof Error ? err.message : 'Could not update category') } }}>{category.isActive === false ? 'Activate' : 'Deactivate'}</button></article>)}</section>}
    {tab === 'reviews' && <section className="tourism-admin-list"><h2>Review moderation</h2>{reviews.map((review) => <article key={review.id}><div><strong>{review.place.nameNp}</strong><p>{review.content}</p><small>{review.status}</small></div>{review.status === 'PENDING' && <div className="tourism-admin-actions"><button onClick={async () => { await call(`/api/v1/tourism/admin/reviews/${review.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'APPROVED' }) }); await reload() }}>Approve</button><button onClick={async () => { await call(`/api/v1/tourism/admin/reviews/${review.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'REJECTED' }) }); await reload() }}>Reject</button></div>}</article>)}</section>}
    {tab === 'reports' && <section className="tourism-admin-list"><h2>Review reports</h2>{reports.map((report) => <article key={report.id}><div><strong>{report.review.place.nameNp} · {report.reason}</strong><p>{report.review.content}</p>{report.details && <p>{report.details}</p>}<small>{report.status}</small></div>{report.status === 'PENDING' && <div className="tourism-admin-actions"><button onClick={async () => { await call(`/api/v1/tourism/admin/review-reports/${report.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'REVIEWED' }) }); await reload() }}>Mark reviewed</button><button onClick={async () => { await call(`/api/v1/tourism/admin/review-reports/${report.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'DISMISSED' }) }); await reload() }}>Dismiss</button></div>}</article>)}</section>}</main>
}
