import { useEffect, useState } from 'react'
import type { ChangeEvent, FormEvent } from 'react'

export type AppealCategory = { id: string; nameNp: string; nameEn: string; icon?: string }
export type Appeal = { id: string; referenceId: string; title: string; description: string; wardId?: string; status: string; supportCount: number; commentCount: number; createdAt: string; imageUrl?: string; category: AppealCategory; comments?: { id: string; content: string; status: string }[]; responses?: { response: string; createdAt: string }[]; history?: { status: string; note?: string; createdAt: string }[] }
const api = '/api/v1/public-appeals'
const visitor = () => { const key = 'chaurpati-visitor-id'; const current = localStorage.getItem(key) ?? crypto.randomUUID(); localStorage.setItem(key, current); return current }

export function AppealsApp() {
  const path = window.location.pathname
  if (path.endsWith('/create')) return <AppealCreate />
  const id = path.split('/').pop()
  return id && id !== 'public-appeals' ? <AppealDetail id={id} /> : <AppealList />
}

function AppealList() {
  const [items, setItems] = useState<Appeal[]>([])
  const [categories, setCategories] = useState<AppealCategory[]>([])
  const [sort, setSort] = useState('newest')
  const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([fetch(api).then((r) => r.json()), fetch(`${api}/categories`).then((r) => r.json())]).then(([data, cats]) => { setItems(data.items ?? []); setCategories(cats) }).finally(() => setLoading(false)) }, [sort])
  return <div className="appeals-page"><AppealsHeader /><section className="appeals-heading"><span className="reference-kicker">जनताको आवाज</span><h1>तपाईंको समस्या, सुझाव र आवाजलाई सम्बन्धित निकायसम्म पुर्‍याऔं।</h1><a className="public-primary" href="/public-appeals/create">＋ समस्या/सुझाव राख्नुहोस्</a></section><div className="appeal-filters"><input placeholder="समस्या खोज्नुहोस्" onChange={(event) => { const value = event.target.value.toLowerCase(); setItems((current) => current.filter((item) => item.title.toLowerCase().includes(value))) }} /><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">नयाँ</option><option value="support">धेरै समर्थन</option><option value="comments">धेरै टिप्पणी</option></select><select><option>सबै वर्ग</option>{categories.map((category) => <option key={category.id}>{category.nameNp}</option>)}</select></div>{loading ? <div className="appeal-empty">लोड हुँदैछ...</div> : items.length === 0 ? <div className="appeal-empty">अहिले कुनै सार्वजनिक समस्या वा सुझाव प्रकाशित गरिएको छैन।<a className="public-primary" href="/public-appeals/create">समस्या/सुझाव राख्नुहोस्</a></div> : <div className="appeal-grid">{items.map((item) => <AppealCard key={item.id} appeal={item} />)}</div>}</div>
}

function AppealsHeader() { return <header className="appeals-header"><a className="reference-logo" href="/"><span className="reference-emblem">CP</span><span><strong>चौरपाटी गाउँपालिका</strong><small>जनताको आवाज</small></span></a><nav><a href="/">गृहपृष्ठ</a><a href="/public-appeals">जनताको आवाज</a><a href="/admin#appeals">Admin</a></nav></header> }
function AppealCard({ appeal }: { appeal: Appeal }) { return <article className="appeal-card"><div className="appeal-card-body">{appeal.imageUrl && <img src={appeal.imageUrl} alt="" />}<div><span className="appeal-category">{appeal.category.icon} {appeal.category.nameNp}</span><h2>{appeal.title}</h2><p>वडा नं. {appeal.wardId ?? '—'} · {new Date(appeal.createdAt).toLocaleDateString()}</p><span className={`appeal-status status-${appeal.status.toLowerCase()}`}>{appeal.status}</span></div></div><div className="appeal-card-footer"><span>👍 {appeal.supportCount} समर्थन</span><span>💬 {appeal.commentCount} टिप्पणी</span><a href={`/public-appeals/${appeal.id}`}>विस्तृत हेर्नुहोस् →</a></div></article> }

function AppealCreate() {
  const [categories, setCategories] = useState<AppealCategory[]>([]); const [form, setForm] = useState({ type: 'PROBLEM', title: '', description: '', wardId: '', categoryId: '', authorName: '', contact: '', consent: false, imageUrl: '' }); const [result, setResult] = useState<Appeal | null>(null); const [error, setError] = useState('')
  useEffect(() => { fetch(`${api}/categories`).then((r) => r.json()).then(setCategories) }, [])
  const photo = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5_000_000) { setError('JPG, PNG वा WEBP फोटो ५ MB भन्दा कम हुनुपर्छ।'); return } const reader = new FileReader(); reader.onload = () => setForm((current) => ({ ...current, imageUrl: String(reader.result) })); reader.readAsDataURL(file) }
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (!form.consent || !form.categoryId) { setError('कृपया वर्ग र सहमति पूरा गर्नुहोस्।'); return } const response = await fetch(api, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, isAnonymous: !form.authorName }) }); if (!response.ok) { setError('दर्ता गर्न सकिएन। फेरि प्रयास गर्नुहोस्।'); return } setResult(await response.json()) }
  if (result) return <div className="appeals-page"><AppealsHeader /><div className="appeal-success"><strong>तपाईंको समस्या/सुझाव सफलतापूर्वक दर्ता भयो।</strong><p>प्रकाशन हुनुअघि यो समीक्षा गरिनेछ।</p><code>{result.referenceId}</code><a className="public-secondary" href="/public-appeals">सबै आवाज हेर्नुहोस्</a></div></div>
  return <div className="appeals-page"><AppealsHeader /><form className="appeal-form" onSubmit={submit}><span className="reference-kicker">जनताको आवाज</span><h1>समस्या वा सुझाव राख्नुहोस्</h1><div className="type-toggle"><label><input type="radio" checked={form.type === 'PROBLEM'} onChange={() => setForm({ ...form, type: 'PROBLEM' })} /> समस्या</label><label><input type="radio" checked={form.type === 'SUGGESTION'} onChange={() => setForm({ ...form, type: 'SUGGESTION' })} /> सुझाव</label></div><label>शीर्षक<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>विवरण<textarea required rows={6} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="form-two"><label>वडा<input value={form.wardId} onChange={(e) => setForm({ ...form, wardId: e.target.value })} /></label><label>वर्ग<select required value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}><option value="">छान्नुहोस्</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.nameNp}</option>)}</select></label></div><label>फोटो<input type="file" accept="image/jpeg,image/png,image/webp" onChange={photo} /></label><p className="privacy-note">कृपया व्यक्तिगत वा निजी स्थानको ठ्याक्कै स्थान नराख्नुहोस्।</p><div className="form-two"><label>नाम (ऐच्छिक)<input value={form.authorName} onChange={(e) => setForm({ ...form, authorName: e.target.value })} /></label><label>सम्पर्क (निजी)<input value={form.contact} onChange={(e) => setForm({ ...form, contact: e.target.value })} /></label></div><label><input type="checkbox" checked={form.consent} onChange={(e) => setForm({ ...form, consent: e.target.checked })} /> सामग्री सार्वजनिक गर्न सहमत छु</label>{error && <div className="save-error">{error}</div>}<button className="public-primary" type="submit">दर्ता गर्नुहोस्</button></form></div>
}

function AppealDetail({ id }: { id: string }) { const [appeal, setAppeal] = useState<Appeal | null>(null); const [comment, setComment] = useState(''); useEffect(() => { fetch(`${api}/${id}`).then((r) => r.json()).then(setAppeal) }, [id]); if (!appeal) return <div className="appeal-empty">लोड हुँदैछ...</div>; const vote = async () => { await fetch(`${api}/${id}/vote`, { method: 'POST', headers: { 'x-visitor-id': visitor() } }); const next = await fetch(`${api}/${id}`).then((r) => r.json()); setAppeal(next) }; const submitComment = async () => { await fetch(`${api}/${id}/comments`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-visitor-id': visitor() }, body: JSON.stringify({ content: comment }) }); setComment(''); }; return <div className="appeals-page"><AppealsHeader /><article className="appeal-detail"><span className="appeal-category">{appeal.category.icon} {appeal.category.nameNp}</span><h1>{appeal.title}</h1><p className="appeal-meta">वडा नं. {appeal.wardId ?? '—'} · {new Date(appeal.createdAt).toLocaleDateString()} · {appeal.status}</p>{appeal.imageUrl && <img className="appeal-detail-image" src={appeal.imageUrl} alt="" />}<p className="appeal-description">{appeal.description}</p><button className="support-button" onClick={vote}>👍 समर्थन {appeal.supportCount}</button><section className="appeal-timeline"><h2>स्थिति इतिहास</h2>{appeal.history?.map((event) => <div key={event.createdAt}><strong>{event.status}</strong><span>{event.note}</span></div>)}</section><section className="appeal-comments"><h2>टिप्पणी ({appeal.commentCount})</h2><textarea value={comment} onChange={(e) => setComment(e.target.value)} placeholder="आफ्नो टिप्पणी लेख्नुहोस्" /><button className="public-secondary" onClick={submitComment}>टिप्पणी पठाउनुहोस्</button>{appeal.comments?.map((item) => <p key={item.id}>{item.content}</p>)}</section></article></div> }
