import { useEffect, useState } from 'react'
import { apiFetch as fetch } from './api-client'
import type { Appeal } from './appeals'
import type { Language } from './language'

export function AppealsHomeSection({ language }: { language: Language }) {
  const en = language === 'en'
  const [items, setItems] = useState<Appeal[]>([])
  const [error, setError] = useState(false)
  useEffect(() => { fetch('/api/v1/public-appeals?sort=support&limit=4').then((response) => { if (!response.ok) throw new Error('Unavailable'); return response.json() }).then((data: { items?: Appeal[] }) => setItems(data.items ?? [])).catch(() => setError(true)) }, [])
  return <section className="appeals-home-section" id="appeals"><header><div><span className="reference-kicker">{en ? 'CITIZEN PARTICIPATION' : 'नागरिक सहभागिता'}</span><h2>{en ? 'Public Voice' : 'जनताको आवाज'}</h2><p>{en ? 'Share an issue or suggestion with the responsible municipality office.' : 'तपाईंको समस्या, सुझाव र आवाज सम्बन्धित निकायसम्म पुर्‍याऔं।'}</p></div><a href="/public-appeals">{en ? 'View all appeals' : 'सबै आवाज हेर्नुहोस्'} →</a></header>{items.length === 0 ? <div className="appeals-home-empty"><p>{error ? (en ? 'Appeals could not be loaded.' : 'निवेदनहरू अहिले लोड गर्न सकिएन।') : (en ? 'No public issues or suggestions have been published yet.' : 'अहिले कुनै सार्वजनिक समस्या वा सुझाव प्रकाशित गरिएको छैन।')}</p><a href="/public-appeals/create">{en ? 'Submit an issue or suggestion' : 'समस्या/सुझाव राख्नुहोस्'}</a></div> : <div className="appeals-home-grid">{items.map((item) => <a className="appeal-home-card" href={`/public-appeals/${item.id}`} key={item.id}><span>{item.category?.icon} {en ? item.category?.nameEn || item.category?.nameNp : item.category?.nameNp}</span><h3>{item.title}</h3><p>{en ? 'Ward' : 'वडा नं.'} {item.wardId ?? '—'} · {new Date(item.createdAt).toLocaleDateString(en ? 'en-US' : 'ne-NP')}</p><strong>{item.status === 'RESOLVED' ? (en ? '✓ Resolved' : '✓ समाधान भयो') : item.status === 'IN_PROGRESS' ? (en ? '◉ In progress' : '◉ समाधान प्रक्रियामा') : (en ? '● Published' : '● प्रकाशित')}</strong><div><b>👍 {item.supportCount} {en ? 'supports' : 'समर्थन'}</b><small>💬 {item.commentCount} {en ? 'comments' : 'टिप्पणी'}</small></div><span className="home-card-detail">{en ? 'View details' : 'विस्तृत हेर्नुहोस्'} →</span></a>)}</div>}<a className="appeals-home-create" href="/public-appeals/create">＋ {en ? 'Submit an issue or suggestion' : 'समस्या/सुझाव राख्नुहोस्'}</a></section>
}
