import { useCallback, useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { GeoJSON, MapContainer, Marker, Polyline, Popup, TileLayer, useMap, useMapEvents } from 'react-leaflet'
import type { LatLngExpression } from 'leaflet'
import L from 'leaflet'
import type { GeoJsonObject } from 'geojson'
import 'leaflet/dist/leaflet.css'
import './map.css'
import { useLanguage } from './language'
import type { Language } from './language'

type Category = { id: string; slug: string; nameNp: string; nameEn: string; icon?: string }
type Place = { id: string; slug: string; nameNp: string; nameEn?: string; descriptionNp?: string; descriptionEn?: string; categoryId: string; category: Category; wardNumber?: number | null; latitude?: number | null; longitude?: number | null; geometry?: string | null; address?: string; phone?: string; email?: string; website?: string; imageUrl?: string; openingHours?: string; sourceName?: string; sourceUrl?: string; isTourism?: boolean }
type Appeal = { id: string; title: string; wardId?: string; status: string; supportCount: number; commentCount: number; latitude: number; longitude: number; category: { nameNp: string; icon?: string } }
type GeoResult = { id: string; name: string; displayName: string; latitude: number; longitude: number; type: string; boundingBox?: number[]; geometry?: GeoJsonObject }
type Boundary = { id: string; name: string; wardNumber?: number | null; layerType?: string; geoJson: GeoJsonObject }
type Point = [number, number]
type Route = { distanceMeters: number; durationSeconds: number; geometry: { coordinates: [number, number][] }; steps: { instruction: string; name: string }[] }
const base = '/api/map'
const api = async <T,>(url: string): Promise<T> => { const response = await fetch(url); if (!response.ok) { const body = await response.json().catch(() => ({})) as { message?: string }; throw new Error(body.message || `Request failed (${response.status})`) } return response.json() as Promise<T> }
const coordinate = (item: { latitude?: number | null; longitude?: number | null }): item is { latitude: number; longitude: number } => Number.isFinite(item.latitude) && Number.isFinite(item.longitude)
const geoCenter = (values: unknown[]): Point | null => { const points: Point[] = []; const walk = (value: unknown) => { if (!Array.isArray(value)) return; if (value.length >= 2 && typeof value[0] === 'number' && typeof value[1] === 'number') { const [lon, lat] = value; if (Number.isFinite(lat) && Number.isFinite(lon) && Math.abs(lat) <= 90 && Math.abs(lon) <= 180) points.push([lat, lon]); return }; value.forEach(walk) }; values.forEach((value) => { if (!value || typeof value !== 'object') return; if ('coordinates' in value) walk((value as { coordinates: unknown }).coordinates); else if ('features' in value) (value as { features: { geometry?: { coordinates?: unknown } }[] }).features.forEach((feature) => walk(feature.geometry?.coordinates)); else if ('geometry' in value) walk((value as { geometry?: { coordinates?: unknown } }).geometry?.coordinates) }); if (!points.length) return null; return [(Math.min(...points.map(([lat]) => lat)) + Math.max(...points.map(([lat]) => lat))) / 2, (Math.min(...points.map(([, lon]) => lon)) + Math.max(...points.map(([, lon]) => lon))) / 2] }
const safeIcon = (value: string) => value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!)
const markerIcon = (symbol: string, appeal = false) => L.divIcon({ className: `place-leaflet-icon${appeal ? ' is-appeal' : ''}`, html: `<span>${safeIcon(symbol)}</span>`, iconSize: [32, 38], iconAnchor: [16, 36], popupAnchor: [0, -34] })

function Viewport({ center, zoom }: { center: Point; zoom: number }) { const map = useMap(); useEffect(() => { map.setView(center, zoom, { animate: true }) }, [map, center, zoom]); return null }
function OriginPicker({ onPick }: { onPick: (point: Point) => void }) { useMapEvents({ click: ({ latlng }) => onPick([latlng.lat, latlng.lng]) }); return null }
function MapTools({ onLocate, locating, onReset }: { onLocate: () => void; locating: boolean; onReset: () => void }) {
  const map = useMap()
  return <div className="map-controls leaflet-map-tools"><button title="Zoom in" aria-label="Zoom in" onClick={() => map.zoomIn()}>+</button><button title="Zoom out" aria-label="Zoom out" onClick={() => map.zoomOut()}>−</button><button onClick={onLocate} disabled={locating} title="My location">◎</button><button onClick={onReset} title="Reset map view">⌖</button><button onClick={() => { const container = map.getContainer(); if (document.fullscreenElement) void document.exitFullscreen(); else if (container.requestFullscreen) void container.requestFullscreen() }} title="Fullscreen map">⛶</button></div>
}

export function ExploreMapPage() {
  const { language, setLanguage } = useLanguage()
  const en = language === 'en'
  const [places, setPlaces] = useState<Place[]>([]); const [appeals, setAppeals] = useState<Appeal[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [boundaries, setBoundaries] = useState<Boundary[]>([])
  const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [ward, setWard] = useState(''); const [selected, setSelected] = useState<Place | Appeal | GeoResult | null>(null)
  const [center, setCenter] = useState<Point | null>(() => { const lat = Number(import.meta.env.VITE_MAP_CENTER_LAT); const lon = Number(import.meta.env.VITE_MAP_CENTER_LON); return Number.isFinite(lat) && Number.isFinite(lon) && (lat !== 0 || lon !== 0) ? [lat, lon] : null })
  const [zoom, setZoom] = useState(13); const [layer, setLayer] = useState('street'); const [showBoundaries, setShowBoundaries] = useState(true); const [origin, setOrigin] = useState<Point | null>(null); const [routeDestination, setRouteDestination] = useState<Point | null>(null); const [route, setRoute] = useState<Route | null>(null)
  const [routeBusy, setRouteBusy] = useState(false); const [routeError, setRouteError] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(true); const [suggestionsOpen, setSuggestionsOpen] = useState(false); const [locating, setLocating] = useState(false)
  const [geoResults, setGeoResults] = useState<GeoResult[]>([]); const [geoBusy, setGeoBusy] = useState(false); const [geoError, setGeoError] = useState('')
  const [routeFromQuery, setRouteFromQuery] = useState(''); const [routeToQuery, setRouteToQuery] = useState(''); const [routeFromResults, setRouteFromResults] = useState<GeoResult[]>([]); const [routeToResults, setRouteToResults] = useState<GeoResult[]>([]); const [routeFromSuggestionsOpen, setRouteFromSuggestionsOpen] = useState(false); const [routeToSuggestionsOpen, setRouteToSuggestionsOpen] = useState(false)

  useEffect(() => { let active = true; setBusy(true); Promise.all([api<Place[]>(`${base}/places`), api<Category[]>(`${base}/categories`), api<Appeal[]>(`${base}/appeals`), api<Boundary[]>(`${base}/boundaries`)]).then(([p, c, a, b]) => { if (!active) return; setPlaces(p); setCategories(c); setAppeals(a); setBoundaries(b); const first = [...p.filter(coordinate), ...a].find(coordinate); const geoPoint = first ? [Number(first.latitude), Number(first.longitude)] as Point : geoCenter([...b.map((item) => item.geoJson), ...p.filter((item) => item.geometry).map((item) => { try { return JSON.parse(item.geometry!) as unknown } catch { return null } })]); if (geoPoint) setCenter((current) => current ?? geoPoint) }).catch((e: Error) => { if (active) setError(e.message) }).finally(() => { if (active) setBusy(false) }); return () => { active = false } }, [])

  useEffect(() => { const term = query.trim(); if (!suggestionsOpen || term.length < 2) { setGeoResults([]); setGeoBusy(false); return }; let active = true; const timer = window.setTimeout(() => { setGeoBusy(true); setGeoError(''); void api<{ results: GeoResult[] }>(`${base}/autocomplete?q=${encodeURIComponent(term)}&lang=${en ? 'en' : 'ne'}`).then((response) => { if (active) setGeoResults(response.results) }).catch((error: Error) => { if (active) setGeoError(error.message) }).finally(() => { if (active) setGeoBusy(false) }) }, 450); return () => { active = false; window.clearTimeout(timer) } }, [query, suggestionsOpen, en])
  useEffect(() => { const term = routeFromQuery.trim(); if (!routeFromSuggestionsOpen || term.length < 2) { setRouteFromResults([]); return }; let active = true; const timer = window.setTimeout(() => { void api<{ results: GeoResult[] }>(`${base}/autocomplete?q=${encodeURIComponent(term)}&lang=${en ? 'en' : 'ne'}`).then((response) => { if (active) setRouteFromResults(response.results) }).catch(() => { if (active) setRouteFromResults([]) }) }, 450); return () => { active = false; window.clearTimeout(timer) } }, [routeFromQuery, routeFromSuggestionsOpen, en])
  useEffect(() => { const term = routeToQuery.trim(); if (!routeToSuggestionsOpen || term.length < 2) { setRouteToResults([]); return }; let active = true; const timer = window.setTimeout(() => { void api<{ results: GeoResult[] }>(`${base}/autocomplete?q=${encodeURIComponent(term)}&lang=${en ? 'en' : 'ne'}`).then((response) => { if (active) setRouteToResults(response.results) }).catch(() => { if (active) setRouteToResults([]) }) }, 450); return () => { active = false; window.clearTimeout(timer) } }, [routeToQuery, routeToSuggestionsOpen, en])

  const filtered = useMemo(() => { const term = query.trim().toLocaleLowerCase(); return places.filter((place) => (!category || place.category.slug === category) && (!ward || place.wardNumber === Number(ward)) && (!term || [place.nameNp, place.nameEn ?? ''].some((name) => name.toLocaleLowerCase().startsWith(term)))) }, [places, category, ward, query])
  const routeFromPlaceMatches = useMemo(() => { const term = routeFromQuery.trim().toLocaleLowerCase(); return term ? places.filter((place) => coordinate(place) && [place.nameNp, place.nameEn ?? ''].some((name) => name.toLocaleLowerCase().startsWith(term))) : [] }, [places, routeFromQuery])
  const routeToPlaceMatches = useMemo(() => { const term = routeToQuery.trim().toLocaleLowerCase(); return term ? places.filter((place) => coordinate(place) && [place.nameNp, place.nameEn ?? ''].some((name) => name.toLocaleLowerCase().startsWith(term))) : [] }, [places, routeToQuery])
  const visibleAppeals = useMemo(() => appeals.filter((item) => !ward || Number(item.wardId) === Number(ward)), [appeals, ward])
  const locate = useCallback(() => { if (!navigator.geolocation) { setError('Location is not supported by this browser.'); return }; setLocating(true); navigator.geolocation.getCurrentPosition(({ coords }) => { const point: Point = [coords.latitude, coords.longitude]; setOrigin(point); setCenter(point); setZoom(15); setLocating(false) }, (e) => { setError(e.code === e.PERMISSION_DENIED ? 'Location permission was denied.' : 'Could not determine your current location.'); setLocating(false) }, { enableHighAccuracy: false, timeout: 10_000, maximumAge: 60_000 }) }, [])
  const selectPlace = (place: Place) => { setSelected(place); setRoute(null); if (coordinate(place)) { const point: Point = [place.latitude, place.longitude]; setCenter(point); setRouteDestination(point); setRouteToQuery(place.nameEn || place.nameNp); setZoom(Math.max(zoom, 15)) }; setSuggestionsOpen(false) }
  useEffect(() => { const slug = new URLSearchParams(window.location.search).get('destination'); const destination = slug && places.find((place) => place.isTourism && place.slug === slug); if (destination && coordinate(destination)) { setSelected(destination); setCenter([destination.latitude, destination.longitude]); setRouteDestination([destination.latitude, destination.longitude]); setRouteToQuery(en ? destination.nameEn || destination.nameNp : destination.nameNp); setZoom(15) } }, [places, en])
  const selectGeoResult = (place: GeoResult) => { setSelected(place); setRoute(null); const point: Point = [place.latitude, place.longitude]; setCenter(point); setRouteDestination(point); setRouteToQuery(place.name); const box = place.boundingBox; const span = box?.length === 4 ? Math.max(box[1] - box[0], box[3] - box[2]) : 2; setZoom(span > 1 ? 10 : span > .2 ? 12 : 15); setSuggestionsOpen(false) }
  const selectAppeal = (item: Appeal) => { setSelected(item); setRoute(null); const point: Point = [item.latitude, item.longitude]; setCenter(point); setRouteDestination(point); setRouteToQuery(item.title) }
  const findRoutePlaces = async (term: string, update: (results: GeoResult[]) => void) => { if (term.trim().length < 2) { setRouteError(en ? 'Enter at least two characters for a place search.' : 'स्थान खोज्न कम्तीमा दुई अक्षर लेख्नुहोस्।'); return }; setRouteError(''); try { const response = await api<{ results: GeoResult[] }>(`${base}/geocode?q=${encodeURIComponent(term.trim())}`); update(response.results); if (!response.results.length) setRouteError(en ? 'No matching place was found.' : 'मिल्दो स्थान भेटिएन।') } catch (e) { setRouteError((e as Error).message) } }
  const chooseRouteFrom = (place: GeoResult) => { setOrigin([place.latitude, place.longitude]); setRouteFromQuery(place.name); setRouteFromSuggestionsOpen(false); setRouteFromResults([]); setRoute(null); setRouteError('') }
  const chooseRouteTo = (place: GeoResult) => { setRouteDestination([place.latitude, place.longitude]); setRouteToQuery(place.name); setRouteToSuggestionsOpen(false); setRouteToResults([]); setRoute(null); setRouteError('') }
  const chooseRouteFromPlace = (place: Place) => { setOrigin([Number(place.latitude), Number(place.longitude)]); setRouteFromQuery(en ? (place.nameEn || place.nameNp) : place.nameNp); setRouteFromSuggestionsOpen(false); setRouteFromResults([]); setRoute(null); setRouteError('') }
  const chooseRouteToPlace = (place: Place) => { setRouteDestination([Number(place.latitude), Number(place.longitude)]); setRouteToQuery(en ? (place.nameEn || place.nameNp) : place.nameNp); setRouteToSuggestionsOpen(false); setRouteToResults([]); setRoute(null); setRouteError('') }
  const searchGeographicNames = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const term = query.trim(); if (term.length < 2) { setGeoError('कम्तीमा दुई अक्षर लेख्नुहोस्।'); return }; setGeoBusy(true); setGeoError(''); setGeoResults([]); try { const result = await api<{ results: GeoResult[] }>(`${base}/geocode?q=${encodeURIComponent(term)}`); setGeoResults(result.results); if (!result.results.length) setGeoError('यो नामको नक्सा परिणाम भेटिएन।'); setSuggestionsOpen(true) } catch (e) { setGeoError((e as Error).message || 'भौगोलिक खोज उपलब्ध छैन।') } finally { setGeoBusy(false) } }
  const resetView = () => { const first = [...places.filter(coordinate), ...appeals].find(coordinate); if (first) { setCenter([Number(first.latitude), Number(first.longitude)]); setZoom(13) } }
  const requestDirections = async () => { if (!origin || !routeDestination) { setRouteError(en ? 'Choose both a starting place and a destination.' : 'सुरु गर्ने स्थान र गन्तव्य दुवै छान्नुहोस्।'); return }; setRouteBusy(true); setRouteError(''); setRoute(null); try { const result = await api<{ available: boolean; message?: string; distanceMeters: number; durationSeconds: number; geometry: Route['geometry']; steps: Route['steps'] }>(`${base}/directions?from=${origin[0]},${origin[1]}&to=${routeDestination[0]},${routeDestination[1]}&mode=driving`); if (!result.available) throw new Error(result.message || (en ? 'No route found' : 'मार्ग भेटिएन')); setRoute(result); setCenter([(origin[0] + routeDestination[0]) / 2, (origin[1] + routeDestination[1]) / 2]); setZoom(Math.min(Math.max(zoom, 12), 15)) } catch (e) { setRouteError((e as Error).message) } finally { setRouteBusy(false) } }
  const tileUrl = layer === 'satellite' ? import.meta.env.VITE_MAP_SATELLITE_TILE_URL : layer === 'terrain' ? import.meta.env.VITE_MAP_TERRAIN_TILE_URL : import.meta.env.VITE_MAP_STREET_TILE_URL || 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
  const googleMapsKey = import.meta.env.VITE_GOOGLE_MAPS_API_KEY?.trim()
  const unavailableLayer = layer !== 'street' && layer !== 'streetview' && !tileUrl
  const selectedAppeal = selected && 'supportCount' in selected

  return <div className="explore-page">
    <header className="explore-header"><a href="/" className="explore-brand"><img src="/chaurpati-emblem.svg" alt=""/><span><strong>{en ? 'Chaurpati Rural Municipality' : 'चौरपाटी गाउँपालिका'}</strong><small>{en ? 'Achham, Sudurpashchim Province' : 'अछाम, सुदूरपश्चिम प्रदेश'}</small></span></a><nav><a href="/">{en ? 'Home' : 'गृहपृष्ठ'}</a><a href="/public-appeals">{en ? 'Public voice' : 'जनताको आवाज'}</a><a className="active" href="/map">▧ {en ? 'Explore map' : 'नक्सा हेर्नुहोस्'}</a><a href="https://chaurpatimun.gov.np/" target="_blank" rel="noreferrer">{en ? 'Contact' : 'सम्पर्क'} ↗</a></nav><button className="explore-language" onClick={() => setLanguage(en ? 'ne' : 'en')}>{en ? 'नेपाली' : 'English'}</button><a className="explore-home-link" href="/">← {en ? 'Portal' : 'पोर्टल'}</a></header>
    <section className="explore-hero"><span>CHAURPATI RURAL MUNICIPALITY · GIS</span><h1>{en ? 'Explore the Map' : 'नक्सा हेर्नुहोस्'}</h1><p>{en ? 'Find verified places and public services in Chaurpati Rural Municipality.' : 'चौरपाटी गाउँपालिकाका प्रमाणित स्थान र सार्वजनिक सेवाहरू नक्सामा खोज्नुहोस्।'}</p></section>
    <main className="explore-layout">
      <aside className="explore-sidebar"><form className="explore-search" role="search" onSubmit={searchGeographicNames}><span aria-hidden="true">⌕</span><input value={query} onChange={(e) => { setQuery(e.target.value); setGeoResults([]); setGeoError(''); setSuggestionsOpen(true) }} onFocus={() => setSuggestionsOpen(true)} onKeyDown={(e) => { if (e.key === 'Escape') setSuggestionsOpen(false) }} placeholder={en ? 'Search a place or service…' : 'स्थान वा सेवा खोज्नुहोस्...'} aria-label={en ? 'Search a place or service' : 'स्थान वा सेवा खोज्नुहोस्'}/><button className="map-search-submit" type="submit" disabled={geoBusy}>{geoBusy ? '…' : en ? 'Search' : 'खोज्नुहोस्'}</button><button type="button" onClick={() => { setQuery(''); setGeoResults([]); setGeoError('') }} aria-label={en ? 'Clear search' : 'खोजी मेटाउनुहोस्'}>×</button></form>
        {suggestionsOpen && query.trim() && <div className="explore-suggestions">{filtered.map((place) => <button key={place.id} onClick={() => selectPlace(place)}><span>{place.category.icon || '●'}</span><span><strong>{en ? (place.nameEn || place.nameNp) : place.nameNp}</strong><small>{en ? place.category.nameEn : place.category.nameNp}{place.wardNumber ? ` · ${en ? 'Ward' : 'वडा'} ${place.wardNumber}` : ''}{place.address ? ` · ${place.address}` : ''}</small></span></button>)}{geoResults.map((place) => <button key={place.id} onClick={() => selectGeoResult(place)}><span>⌖</span><span><strong>{place.name}</strong><small>{place.displayName}</small></span></button>)}{geoBusy && <p>{en ? 'Searching the map…' : 'नक्सामा खोज्दैछ…'}</p>}{geoError && <p>{geoError}</p>}{!filtered.length && !geoResults.length && !geoBusy && !geoError && <p>{en ? 'No place names start with this text. Press Search to search the map.' : 'यो अक्षरबाट सुरु हुने नाम भेटिएन। नक्सामा खोज्न खोज्नुहोस् थिच्नुहोस्।'}</p>}<small className="geocoder-credit">Geographic results © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a></small></div>}
        <section className="explore-filters"><h2>{en ? 'Map filters' : 'देखाउने वर्ग'}</h2><button className={!category ? 'filter-chip selected' : 'filter-chip'} onClick={() => setCategory('')}>{en ? 'All places' : 'सबै स्थान'}</button>{categories.map((item) => <button key={item.id} className={category === item.slug ? 'filter-chip selected' : 'filter-chip'} onClick={() => setCategory(category === item.slug ? '' : item.slug)}><span>{item.icon || '•'}</span>{en ? item.nameEn : item.nameNp}</button>)}<label className="ward-select">{en ? 'Select ward' : 'वडा छान्नुहोस्'}<select value={ward} onChange={(e) => setWard(e.target.value)}><option value="">{en ? 'All wards' : 'सबै वडा'}</option>{Array.from({ length: 7 }, (_, i) => <option value={i + 1} key={i + 1}>{en ? `Ward ${i + 1}` : `वडा नं. ${i + 1}`}</option>)}</select></label><label className="boundary-toggle"><input type="checkbox" checked={showBoundaries} onChange={(e) => setShowBoundaries(e.target.checked)}/> {en ? 'Show available ward boundaries' : 'उपलब्ध आधिकारिक वडा सीमा'}</label>{ward && !boundaries.some((boundary) => boundary.wardNumber === Number(ward)) && <small className="boundary-unavailable">{en ? `Ward ${ward} boundary data has not been published.` : `वडा ${ward} को सीमा नक्सा डेटा प्रकाशित छैन।`}</small>}<small>{filtered.length + visibleAppeals.length} {en ? 'public places' : 'सार्वजनिक स्थान'}</small></section>
        <div className="explore-trust">ⓘ {en ? 'Only verified, publicly published places are shown. Available ward boundaries include their source.' : 'प्रमाणित तथा सार्वजनिक रूपमा प्रकाशित स्थान मात्र देखाइएका छन्। वडा सीमा उपलब्ध भएमा स्रोतसहित देखाइन्छ।'}</div>
      </aside>
      <section className="explore-map-column"><div className="explore-map leaflet-map-shell" aria-label="चौरपाटी सार्वजनिक स्थानको नक्सा">
        {center ? (layer === 'streetview' ? (googleMapsKey ? <iframe className="google-street-view" title={en ? 'Google Street View' : 'गुगल सडक दृश्य'} src={`https://www.google.com/maps/embed/v1/streetview?key=${encodeURIComponent(googleMapsKey)}&location=${center[0]},${center[1]}`} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade"/> : <div className="street-view-setup"><strong>{en ? 'Google Street View setup required' : 'गुगल सडक दृश्य सेटअप आवश्यक छ'}</strong><p>{en ? 'Add a Google Maps Embed API key to VITE_GOOGLE_MAPS_API_KEY in frontend/.env, then restart the frontend.' : 'frontend/.env मा VITE_GOOGLE_MAPS_API_KEY थपेर फ्रन्टएन्ड पुनः सुरु गर्नुहोस्।'}</p></div>) : <MapContainer center={center as LatLngExpression} zoom={zoom} scrollWheelZoom zoomControl={false} className="leaflet-map-view" preferCanvas>
          {!unavailableLayer && <TileLayer url={tileUrl} attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>' maxZoom={19}/>}<Viewport center={center} zoom={zoom}/><OriginPicker onPick={(point) => { setOrigin(point); setRouteFromQuery(en ? 'Map point' : 'नक्साको स्थान') }}/>
          {showBoundaries && boundaries.map((boundary) => { const activeWard = Boolean(ward && boundary.wardNumber === Number(ward)); return <GeoJSON key={boundary.id} data={boundary.geoJson as GeoJsonObject} style={{ color: activeWard ? '#173329' : '#08794f', weight: activeWard ? 5 : 2, dashArray: activeWard ? undefined : '7 5', fillColor: activeWard ? '#08794f' : '#13845b', fillOpacity: activeWard ? .2 : .08 }}/> })}
          {route && <Polyline positions={route.geometry.coordinates.map(([lon, lat]) => [lat, lon] as LatLngExpression)} pathOptions={{ color: '#1388e8', weight: 5 }}/>} {origin && <Marker position={origin as LatLngExpression} icon={markerIcon('●', true)}><Popup>Starting point{origin === center ? '' : ' · approximate'}</Popup></Marker>}
          {filtered.filter(coordinate).map((place) => <Marker key={place.id} position={[place.latitude, place.longitude] as LatLngExpression} icon={markerIcon(place.isTourism ? '🌿' : place.category.icon || '●')} eventHandlers={{ click: () => selectPlace(place) }}><Popup><strong>{place.nameNp}</strong><br/>{place.category.nameNp}{place.wardNumber ? ` · वडा ${place.wardNumber}` : ''}<br/>{place.isTourism ? <a href={`/tourism/${encodeURIComponent(place.slug)}`}>विस्तृत हेर्नुहोस् ↗</a> : <button onClick={() => selectPlace(place)}>विवरण हेर्नुहोस्</button>}</Popup></Marker>)}
          {selected && 'displayName' in selected && selected.geometry && <GeoJSON key={`search-boundary-${selected.id}`} data={selected.geometry} style={{ color: '#172d24', weight: 5, fillColor: '#08794f', fillOpacity: .14 }}/>}{geoResults.map((place) => <Marker key={place.id} position={[place.latitude, place.longitude]} icon={markerIcon('⌖')} eventHandlers={{ click: () => selectGeoResult(place) }}><Popup><strong>{place.name}</strong><br/>{place.displayName}<br/><small>OpenStreetMap search result · municipal record not verified</small></Popup></Marker>)}
          {filtered.filter((place) => !coordinate(place) && Boolean(place.geometry)).map((place) => <GeometryPlace key={place.id} place={place} active={selected?.id === place.id} onSelect={() => selectPlace(place)}/>)}
          {visibleAppeals.map((item) => <Marker key={item.id} position={[item.latitude, item.longitude]} icon={markerIcon('⚑', true)} eventHandlers={{ click: () => selectAppeal(item) }}><Popup><strong>{item.title}</strong><br/>वडा नं. {item.wardId || '—'} · स्थान अनुमानित हो<br/><a href={`/public-appeals/${item.id}`}>निवेदन हेर्नुहोस् ↗</a></Popup></Marker>)}
          <MapTools onLocate={locate} locating={locating} onReset={resetView}/>
        </MapContainer>) : <div className="map-empty"><span>▧</span><strong>{en ? 'Waiting for verified places' : 'प्रमाणित स्थानको प्रतीक्षामा'}</strong><p>{en ? 'An administrator must publish a verified place with coordinates, or choose My location.' : 'नक्सामा स्थान देखाउन व्यवस्थापकले प्रमाणित निर्देशाङ्कसहित स्थान प्रकाशित गर्नुपर्छ। वा मेरो स्थान थिच्नुहोस्।'}</p><button onClick={locate}>{en ? 'Use my location' : 'मेरो स्थान प्रयोग गर्नुहोस्'}</button></div>}
        {unavailableLayer && <div className="map-layer-unavailable">यो नक्सा तह कन्फिगर गरिएको छैन · This layer is not configured</div>}
        {center && <div className="map-layer-switch"><label>{en ? 'Map layer' : 'नक्सा तह'}<select aria-label={en ? 'Map layer' : 'नक्सा तह'} value={layer} onChange={(e) => setLayer(e.target.value)}><option value="street">{en ? 'Map' : 'नक्सा'}</option><option value="satellite">{en ? 'Satellite' : 'उपग्रह'}</option><option value="terrain">{en ? 'Terrain' : 'भू-भाग'}</option><option value="streetview">{en ? 'Street View' : 'सडक दृश्य'}</option></select></label></div>}
      </div><div className="map-status">{error ? <span role="alert">{error}</span> : busy ? (en ? 'Loading map data…' : 'नक्सा डाटा लोड हुँदैछ…') : `${filtered.length} ${en ? 'places' : 'स्थान'} · ${boundaries.length} ${en ? 'published boundaries' : 'प्रकाशित सीमा'}`}</div></section>
      <aside className="explore-detail"><div className="detail-heading"><div><span className="map-eyebrow">{en ? 'Place details' : 'स्थान विवरण'}</span><h2>{selected ? (selectedAppeal ? (selected as Appeal).title : ('displayName' in selected ? selected.name : en ? ((selected as Place).nameEn || (selected as Place).nameNp) : (selected as Place).nameNp)) : (en ? 'Select a place on the map' : 'नक्सामा स्थान छान्नुहोस्')}</h2></div>{selected && <button aria-label={en ? 'Close details' : 'Close details'} onClick={() => { setSelected(null); setRoute(null) }}>×</button>}</div>
        {selected && (selectedAppeal ? <><p className="detail-category">⚑ {en ? 'Public voice · Ward' : 'जनताको आवाज · वडा नं.'} {(selected as Appeal).wardId || '—'}</p><p className="detail-body">{en ? 'This is an approximate location. Personal identity and contact details are not shown.' : 'यो स्थान अनुमानित हो। व्यक्तिको पहिचान वा सम्पर्क विवरण देखाइँदैन।'}</p><p className="detail-meta">{(selected as Appeal).supportCount} {en ? 'supports' : 'समर्थन'} · {(selected as Appeal).commentCount} {en ? 'comments' : 'टिप्पणी'} · {(selected as Appeal).status}</p><a className="detail-primary" href={`/public-appeals/${selected.id}`}>{en ? 'View appeal' : 'निवेदन हेर्नुहोस्'} ↗</a></> : 'displayName' in selected ? <><p className="detail-category">{en ? 'Geographic search result · OpenStreetMap' : 'भौगोलिक खोज परिणाम · OpenStreetMap'}</p><p className="detail-body">{selected.displayName}</p><p className="detail-meta">{en ? 'This result is not a municipality-verified place record.' : 'यो खोज परिणाम नगरपालिका द्वारा प्रमाणित स्थान अभिलेख होइन।'}</p>{!selected.geometry && <p className="detail-meta">{en ? 'No boundary is available for this result; only its map pin is shown.' : 'यस नक्सा परिणामको सीमा उपलब्ध छैन; स्थानको पिन मात्र देखाइएको छ।'}</p>}</> : <PlaceDetails place={selected as Place} language={language}/>)}
        <section className="route-panel"><h3>{en ? 'Directions' : 'दिशा-निर्देशन'}</h3>
          <div className="route-place-fields">
            <label>{en ? 'From any place' : 'सुरु गर्ने स्थान'}<div className="route-place-search"><input value={routeFromQuery} onChange={(event) => { setRouteFromQuery(event.target.value); setRouteFromResults([]); setRoute(null); setRouteFromSuggestionsOpen(true) }} onFocus={() => setRouteFromSuggestionsOpen(true)} placeholder={en ? 'Search starting place…' : 'सुरु गर्ने स्थान खोज्नुहोस्…'}/><button type="button" onClick={() => void findRoutePlaces(routeFromQuery, setRouteFromResults)}>{en ? 'Find' : 'खोज्नुहोस्'}</button></div></label>
            {routeFromResults.map((place) => <button className="route-place-result" type="button" key={place.id} onClick={() => chooseRouteFrom(place)}>{place.name}<small>{place.displayName}</small></button>)}
            {routeFromSuggestionsOpen && routeFromPlaceMatches.map((place) => <button className="route-place-result" type="button" key={`from-${place.id}`} onClick={() => chooseRouteFromPlace(place)}>{en ? (place.nameEn || place.nameNp) : place.nameNp}<small>{place.address || `${en ? 'Ward' : '???'} ${place.wardNumber ?? ''} ? ${en ? place.category.nameEn : place.category.nameNp}`}</small></button>)}
            <label>{en ? 'To any place' : 'गन्तव्य स्थान'}<div className="route-place-search"><input value={routeToQuery} onChange={(event) => { setRouteToQuery(event.target.value); setRouteToResults([]); setRoute(null); setRouteToSuggestionsOpen(true) }} onFocus={() => setRouteToSuggestionsOpen(true)} placeholder={en ? 'Search destination…' : 'गन्तव्य खोज्नुहोस्…'}/><button type="button" onClick={() => void findRoutePlaces(routeToQuery, setRouteToResults)}>{en ? 'Find' : 'खोज्नुहोस्'}</button></div></label>
            {routeToResults.map((place) => <button className="route-place-result" type="button" key={place.id} onClick={() => chooseRouteTo(place)}>{place.name}<small>{place.displayName}</small></button>)}
          </div>
          {routeToSuggestionsOpen && routeToPlaceMatches.map((place) => <button className="route-place-result" type="button" key={`to-${place.id}`} onClick={() => chooseRouteToPlace(place)}>{en ? (place.nameEn || place.nameNp) : place.nameNp}<small>{place.address || `${en ? 'Ward' : '???'} ${place.wardNumber ?? ''} ? ${en ? place.category.nameEn : place.category.nameNp}`}</small></button>)}
          <p>{en ? 'From:' : 'बाट:'} {origin ? `${origin[0].toFixed(5)}, ${origin[1].toFixed(5)}` : (en ? 'Choose a place above, use My location, or click the map' : 'माथि स्थान छान्नुहोस्, मेरो स्थान प्रयोग गर्नुहोस् वा नक्सामा थिच्नुहोस्')}<br/>{en ? 'To:' : 'सम्म:'} {routeDestination ? `${routeDestination[0].toFixed(5)}, ${routeDestination[1].toFixed(5)}` : (en ? 'Choose any destination above' : 'माथि कुनै गन्तव्य छान्नुहोस्')}</p>
          <div className="route-options"><button onClick={locate} disabled={locating}>◎ {en ? 'Use my location as start' : 'मेरो स्थानबाट सुरु गर्नुहोस्'}</button><span>🚗 {en ? 'Car · based on routing service' : 'कार · मार्ग सेवा अनुसार'}</span><span className="mode-disabled">{en ? 'Motorcycle / walking unavailable' : 'मोटरसाइकल / हिँड्ने उपलब्ध छैन'}</span></div>
          {route && <div className="route-result"><strong>{(route.distanceMeters / 1000).toFixed(1)} km · {Math.max(1, Math.round(route.durationSeconds / 60))} {en ? 'min' : 'मिनेट'}</strong><ol>{route.steps.filter((step) => step.instruction !== 'depart' && step.instruction !== 'arrive').slice(0, 8).map((step, index) => <li key={`${step.name}-${index}`}>{step.instruction}{step.name && ` · ${step.name}`}</li>)}</ol><small>{en ? 'OSRM route estimate; road and traffic conditions may vary.' : 'OSRM मार्ग अनुमान; सडक र यातायात अवस्था फरक हुन सक्छ।'}</small></div>}
          {routeError && <p className="route-error" role="alert">{routeError}</p>}<button className="detail-primary route-button" disabled={!origin || !routeDestination || routeBusy} onClick={() => void requestDirections()}>{routeBusy ? (en ? 'Finding route…' : 'मार्ग खोज्दैछ…') : (en ? 'Find route' : 'मार्ग खोज्नुहोस्')}</button>
        </section>
        <section className="detail-list"><h3>{en ? 'Places' : 'स्थानहरू'} {busy && '…'}</h3>{filtered.slice(0, 12).map((place) => <button key={place.id} className={selected?.id === place.id ? 'selected' : ''} onClick={() => selectPlace(place)}><span>{place.category.icon || '●'}</span><span><strong>{en ? place.nameEn || place.nameNp : place.nameNp}</strong><small>{en ? place.category.nameEn : place.category.nameNp}{place.wardNumber ? ` · ${en ? 'Ward' : 'वडा'} ${place.wardNumber}` : ''}</small></span></button>)}{!filtered.length && !busy && <p>{en ? 'No published places are available.' : 'प्रकाशित स्थान उपलब्ध छैन।'}</p>}</section>
      </aside>
    </main>
  </div>
}

function GeometryPlace({ place, active, onSelect }: { place: Place; active: boolean; onSelect: () => void }) {
  const data = useMemo(() => { try { return JSON.parse(place.geometry || 'null') as GeoJsonObject | null } catch { return null } }, [place.geometry])
  return data ? <GeoJSON data={data} style={{ color: active ? '#172d24' : '#08794f', weight: active ? 5 : 2, fillColor: '#13845b', fillOpacity: active ? .2 : .06 }} eventHandlers={{ click: onSelect }}/> : null
}

function PlaceDetails({ place, language }: { place: Place; language: Language }) { const en = language === 'en'; return <><p className="detail-category">{place.category.icon || '●'} {en ? place.category.nameEn : place.category.nameNp}{place.wardNumber ? ` · ${en ? 'Ward' : 'वडा नं.'} ${place.wardNumber}` : ''}</p>{place.imageUrl && <img className="place-photo" src={place.imageUrl} alt={en ? place.nameEn || place.nameNp : place.nameNp} loading="lazy"/>}{(en ? place.descriptionEn : place.descriptionNp) && <p className="detail-body">{en ? place.descriptionEn : place.descriptionNp}</p>}{place.address && <p className="detail-meta">⌖ {place.address}</p>}{place.phone && <p className="detail-meta">☎ {place.phone}</p>}{place.email && <a className="detail-meta" href={`mailto:${place.email}`}>{place.email}</a>}{place.openingHours && <p className="detail-meta">◷ {place.openingHours}</p>}{place.sourceName && <p className="detail-verified">✓ {place.sourceName} · {en ? 'Verified' : 'प्रमाणीकरण भएको'}</p>}{place.website && <a className="detail-meta" href={place.website} target="_blank" rel="noreferrer">{en ? 'Website' : 'वेबसाइट'} ↗</a>}</> }
