import { useEffect, useMemo, useState } from 'react'
import { useLanguage } from './language'
import './tourism.css'

type Category = { id: string; slug: string; nameNp: string; nameEn: string; icon?: string | null }
type TourismImage = { id: string; url: string; altText?: string | null; captionNp?: string | null; captionEn?: string | null; isFeatured: boolean }
export type TourismPlace = {
  id: string; slug: string; nameNp: string; nameEn?: string | null; wardNumber?: number | null; category: Category
  shortDescriptionNp?: string | null; shortDescriptionEn?: string | null; descriptionNp?: string | null; descriptionEn?: string | null
  imageUrl?: string | null; tourismImages?: TourismImage[]; latitude?: number | null; longitude?: number | null
  viewCount: number; averageRating: number; ratingCount: number; historyNp?: string | null; historyEn?: string | null
  culturalSignificanceNp?: string | null; culturalSignificanceEn?: string | null; religiousSignificanceNp?: string | null; religiousSignificanceEn?: string | null
  naturalFeaturesNp?: string | null; naturalFeaturesEn?: string | null; activitiesNp?: string | null; activitiesEn?: string | null
  bestTimeNp?: string | null; bestTimeEn?: string | null; howToReachNp?: string | null; howToReachEn?: string | null
  facilitiesNp?: string | null; facilitiesEn?: string | null; safetyInfoNp?: string | null; safetyInfoEn?: string | null
  tourismReviews?: { id: string; content: string; createdAt: string }[]
}
type PageData = { items: TourismPlace[]; total: number; page: number; pages: number }
const visitorKey = 'chaurpati-appeal-session'

async function visitorToken() {
  let token = localStorage.getItem(visitorKey)
  if (token) return token
  const response = await fetch('/api/v1/public-appeals/visitor-token')
  if (!response.ok) throw new Error('Visitor session unavailable')
  token = (await response.json() as { token: string }).token
  localStorage.setItem(visitorKey, token)
  return token
}
async function visitorRequest(url: string, init?: RequestInit) {
  const token = await visitorToken()
  return fetch(url, { ...init, headers: { 'Content-Type': 'application/json', 'x-visitor-token': token, ...(init?.headers || {}) } })
}
const copy = {
  ne: { title: 'पर्यटकीय स्थलहरू', subtitle: 'चौरपाटी गाउँपालिकाका प्राकृतिक, धार्मिक, ऐतिहासिक तथा सांस्कृतिक गन्तव्यहरू खोज्नुहोस्।', explore: 'EXPLORE CHAURPATI', search: 'पर्यटकीय स्थल खोज्नुहोस्... (जस्तै: मन्दिर, ताल, डाँडा, झरना)', find: 'खोज्नुहोस्', allWards: 'सबै वडा', allCategories: 'सबै श्रेणी', popular: 'लोकप्रियता अनुसार', newest: 'नयाँ थपिएका', rating: 'उच्च रेटिङ', mostViewed: 'धेरै हेरिएका', az: 'नाम A–Z', ward: 'वडा नं.', detail: 'विस्तृत हेर्नुहोस्', empty: 'तपाईंले खोज्नुभएको पर्यटकीय स्थल फेला परेन।', unavailable: 'हाल कुनै पर्यटकीय स्थल प्रकाशित गरिएको छैन।', error: 'पर्यटकीय विवरण लोड हुन सकेन। फेरि प्रयास गर्नुहोस्।', noImage: 'तस्बिर उपलब्ध छैन', views: 'पटक हेरिएको', images: 'तस्बिरहरू', back: 'पर्यटकीय स्थलहरू', about: 'यस स्थानबारे', history: 'इतिहास', culture: 'सांस्कृतिक महत्व', religion: 'धार्मिक महत्व', nature: 'प्राकृतिक विशेषता', activities: 'यहाँका प्रमुख गतिविधिहरू', bestTime: 'भ्रमणका लागि उपयुक्त समय', directions: 'दिशा निर्देशन', facilities: 'उपलब्ध सुविधा', safety: 'सुरक्षा जानकारी', unavailableInfo: 'जानकारी उपलब्ध छैन।', street: 'स्ट्रिट भ्यू हाल उपलब्ध छैन।', reviews: 'समीक्षाहरू', noReviews: 'अहिलेसम्म कुनै समीक्षा छैन।', rate: 'यस स्थानलाई मूल्याङ्कन गर्नुहोस्', write: 'आफ्नो अनुभव लेख्नुहोस्', send: 'समीक्षा पठाउनुहोस्', pending: 'समीक्षा जाँचका लागि पठाइयो।', saved: 'मनपर्नेमा सुरक्षित', save: 'मनपर्नेमा राख्नुहोस्', map: 'नक्सामा हेर्नुहोस्', photosMissing: 'यस स्थानका थप तस्बिरहरू हाल उपलब्ध छैनन्।', report: 'समीक्षा रिपोर्ट गर्नुहोस्', reported: 'रिपोर्ट पठाइयो।' },
  en: { title: 'Tourism Places', subtitle: 'Explore Chaurpati’s natural, religious, historical, and cultural destinations.', explore: 'EXPLORE CHAURPATI', search: 'Search tourism places (temple, lake, hill, waterfall...)', find: 'Search', allWards: 'All wards', allCategories: 'All categories', popular: 'Most popular', newest: 'Recently added', rating: 'Highest rated', mostViewed: 'Most viewed', az: 'Name A–Z', ward: 'Ward', detail: 'View details', empty: 'No tourism places match your search.', unavailable: 'No tourism places have been published yet.', error: 'Tourism places could not be loaded. Please try again.', noImage: 'Photo unavailable', views: 'views', images: 'Photos', back: 'Tourism places', about: 'About this place', history: 'History', culture: 'Cultural significance', religion: 'Religious significance', nature: 'Natural features', activities: 'Things to do', bestTime: 'Best time to visit', directions: 'Directions', facilities: 'Facilities', safety: 'Safety information', unavailableInfo: 'Information unavailable.', street: 'Street View is not available for this place.', reviews: 'Reviews', noReviews: 'There are no reviews yet.', rate: 'Rate this place', write: 'Share your experience', send: 'Submit review', pending: 'Your review was sent for moderation.', saved: 'Saved to favorites', save: 'Save to favorites', map: 'View on map', photosMissing: 'More photos are not available for this place yet.', report: 'Report review', reported: 'Report submitted.' },
}
function imageOf(place: TourismPlace) { return place.tourismImages?.find((image) => image.isFeatured)?.url || place.imageUrl || place.tourismImages?.[0]?.url || '' }

export function TourismCard({ place }: { place: TourismPlace }) {
  const { language } = useLanguage(); const t = copy[language]
  const name = language === 'ne' ? place.nameNp : place.nameEn || place.nameNp
  const desc = language === 'ne' ? place.shortDescriptionNp || place.descriptionNp : place.shortDescriptionEn || place.descriptionEn || place.shortDescriptionNp
  const image = imageOf(place)
  return <article className="tourism-card"><a className="tourism-card-photo" href={`/tourism/${encodeURIComponent(place.slug)}`} aria-label={`${t.detail}: ${name}`}>
    {image ? <img src={image} alt={place.tourismImages?.find((item) => item.url === image)?.altText || name} loading="lazy" /> : <span className="tourism-no-image">{t.noImage}</span>}
    <span className="tourism-category">{place.category.icon} {language === 'ne' ? place.category.nameNp : place.category.nameEn}</span>
    {!!place.tourismImages?.length && <span className="tourism-image-count">▧ {place.tourismImages.length}</span>}
  </a><div className="tourism-card-body"><h2><a href={`/tourism/${encodeURIComponent(place.slug)}`}>{name}</a></h2>
    <div className="tourism-card-meta"><span>⌖ {t.ward} {place.wardNumber ?? '—'}</span><span>★ {Number(place.averageRating).toFixed(1)} ({place.ratingCount})</span></div>
    <p>{desc || t.unavailableInfo}</p>{place.latitude != null && place.longitude != null && <a className="tourism-direction-link" href={`/map?destination=${encodeURIComponent(place.slug)}`}>{language === 'ne' ? 'नक्सामा स्थान हेर्नुहोस्' : 'See location'} ↗</a>}<div className="tourism-card-footer"><small>◉ {place.viewCount.toLocaleString()} {t.views}</small><a href={`/tourism/${encodeURIComponent(place.slug)}`}>{t.detail} →</a></div>
  </div></article>
}

export function PopularTourism() {
  const { language } = useLanguage(); const t = copy[language]; const [places, setPlaces] = useState<TourismPlace[]>([])
  useEffect(() => { fetch('/api/v1/tourism/places?sort=popular&limit=3').then((response) => response.ok ? response.json() as Promise<PageData> : Promise.reject()).then((data) => setPlaces(data.items)).catch(() => setPlaces([])) }, [])
  if (!places.length) return null
  return <section className="tourism-home-section"><header><div><span className="section-kicker">{t.explore}</span><h2>{language === 'ne' ? 'लोकप्रिय पर्यटकीय स्थल' : 'Popular tourism places'}</h2></div><a href="/tourism">{t.back} →</a></header><div className="tourism-home-grid">{places.map((place) => <TourismCard key={place.id} place={place} />)}</div></section>
}

export function TourismPage() {
  const { language } = useLanguage(); const t = copy[language]
  const [data, setData] = useState<PageData | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [q, setQ] = useState(''); const [term, setTerm] = useState(''); const [ward, setWard] = useState(''); const [category, setCategory] = useState(''); const [sort, setSort] = useState('popular'); const [page, setPage] = useState(1); const [error, setError] = useState(false)
  useEffect(() => { fetch('/api/v1/tourism/categories').then((r) => r.ok ? r.json() as Promise<Category[]> : Promise.reject()).then(setCategories).catch(() => setCategories([])) }, [])
  useEffect(() => { const timer = window.setTimeout(() => setTerm(q.trim()), 250); return () => window.clearTimeout(timer) }, [q])
  useEffect(() => { const params = new URLSearchParams({ page: String(page), limit: '12', sort }); if (term) params.set('q', term); if (ward) params.set('ward', ward); if (category) params.set('category', category); setError(false); fetch(`/api/v1/tourism/places?${params}`).then((r) => r.ok ? r.json() as Promise<PageData> : Promise.reject()).then((result) => setData(result)).catch(() => { setError(true); setData(null) }) }, [term, ward, category, sort, page])
  const resetPage = (setter: (value: string) => void) => (value: string) => { setter(value); setPage(1) }
  const hero = data?.items.map(imageOf).find(Boolean)
  return <main className="tourism-page"><TourismHeader /><section className="tourism-hero">{hero && <img className="tourism-hero-image" src={hero} alt="" fetchPriority="high" />}<div className="tourism-hero-inner"><span>{t.explore}</span><h1>{t.title}</h1><p>{t.subtitle}</p><em>“{language === 'ne' ? 'प्रकृतिको काखमा सुन्दर चौरपाटी' : 'Beautiful Chaurpati in nature’s embrace'}”</em></div></section>
    <section className="tourism-controls"><form className="tourism-search" onSubmit={(event) => { event.preventDefault(); setTerm(q.trim()); setPage(1) }}><span>⌕</span><input aria-label={t.search} value={q} onChange={(event) => resetPage(setQ)(event.target.value)} placeholder={t.search} /><button>{t.find}</button></form>
      <label>⌖ <select value={ward} onChange={(event) => { setWard(event.target.value); setPage(1) }} aria-label={t.ward}><option value="">{t.allWards}</option>{Array.from({ length: 7 }, (_, i) => <option value={i + 1} key={i}>{t.ward} {i + 1}</option>)}</select></label>
      <label>▦ <select value={category} onChange={(event) => { setCategory(event.target.value); setPage(1) }} aria-label={t.allCategories}><option value="">{t.allCategories}</option>{categories.map((item) => <option key={item.id} value={item.slug}>{language === 'ne' ? item.nameNp : item.nameEn}</option>)}</select></label>
      <label>☷ <select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1) }} aria-label="Sort"><option value="popular">{t.popular}</option><option value="newest">{t.newest}</option><option value="rating">{t.rating}</option><option value="views">{t.mostViewed}</option><option value="name-en">{t.az}</option><option value="name-np">नाम नेपाली वर्णक्रम</option></select></label>
    </section><section className="tourism-results">{error ? <div className="tourism-empty">{t.error}</div> : !data ? <div className="tourism-empty">…</div> : data.items.length ? <><div className="tourism-grid">{data.items.map((place) => <TourismCard key={place.id} place={place} />)}</div>{data.pages > 1 && <nav className="tourism-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>←</button><span>{page} / {data.pages}</span><button disabled={page >= data.pages} onClick={() => setPage(page + 1)}>→</button></nav>}</> : <div className="tourism-empty">{data.total ? t.empty : t.unavailable}</div>}</section><TourismFooter /></main>
}

function TourismHeader() { const { language, setLanguage } = useLanguage(); return <header className="tourism-header"><a className="tourism-brand" href="/"><img src="/chaurpati-emblem.svg" alt="" /><span><b>{language === 'ne' ? 'चौरपाटी गाउँपालिका' : 'Chaurpati Rural Municipality'}</b><small>{language === 'ne' ? 'अछाम, सुदूरपश्चिम प्रदेश' : 'Achham, Sudurpashchim Province'}</small></span></a><nav><a href="/">{language === 'ne' ? 'गृहपृष्ठ' : 'Home'}</a><a href="/map">{language === 'ne' ? 'नक्सा हेर्नुहोस्' : 'Explore map'}</a><a className="active" href="/tourism">{language === 'ne' ? 'पर्यटकीय स्थल' : 'Tourism'}</a></nav><button onClick={() => setLanguage(language === 'ne' ? 'en' : 'ne')}>{language === 'ne' ? 'English' : 'नेपाली'}</button></header> }
function TourismFooter() { const { language } = useLanguage(); return <footer className="tourism-footer"><a href="/">{language === 'ne' ? 'चौरपाटी गाउँपालिका' : 'Chaurpati Rural Municipality'}</a><a href="/map">{language === 'ne' ? 'नक्सा' : 'Explore map'}</a></footer> }

export function TourismDetailPage({ slug }: { slug: string }) {
  const { language } = useLanguage(); const t = copy[language]
  const [place, setPlace] = useState<TourismPlace | null>(null); const [error, setError] = useState(false); const [viewer, setViewer] = useState<number | null>(null); const [rating, setRating] = useState(0); const [review, setReview] = useState(''); const [message, setMessage] = useState(''); const [saved, setSaved] = useState(false)
  useEffect(() => { let active = true; fetch(`/api/v1/tourism/places/${encodeURIComponent(slug)}`).then((r) => r.ok ? r.json() as Promise<TourismPlace> : Promise.reject()).then(async (item) => { if (!active) return; setPlace(item); try { const response = await visitorRequest(`/api/v1/tourism/places/${item.id}/view`, { method: 'POST' }); if (response.ok) { const view = await response.json() as { viewCount: number }; if (active) setPlace((current) => current ? { ...current, viewCount: view.viewCount } : current) } } catch { /* Detail remains readable without analytics. */ } }).catch(() => active && setError(true)); return () => { active = false } }, [slug])
  const placeId = place?.id
  useEffect(() => { if (!placeId) return; visitorRequest(`/api/v1/tourism/places/${placeId}/favorite`).then((r) => r.ok ? r.json() as Promise<{ saved: boolean }> : Promise.reject()).then((result) => setSaved(result.saved)).catch(() => undefined) }, [placeId])
  const images = useMemo(() => place?.tourismImages?.length ? place.tourismImages : place?.imageUrl ? [{ id: place.id, url: place.imageUrl, isFeatured: true }] : [], [place])
  const local = (np?: string | null, en?: string | null) => (language === 'ne' ? np : en) || (language === 'ne' ? en : np) || t.unavailableInfo
  const rate = async (value: number) => { if (!place) return; try { const r = await visitorRequest(`/api/v1/tourism/places/${place.id}/rating`, { method: 'POST', body: JSON.stringify({ rating: value }) }); if (!r.ok) throw new Error(); const result = await r.json() as { averageRating: number; ratingCount: number; yourRating: number }; setRating(value); setPlace({ ...place, ...result }) } catch { setMessage(language === 'ne' ? 'मूल्याङ्कन पठाउन सकिएन। फेरि प्रयास गर्नुहोस्।' : 'Rating could not be submitted. Please try again.') } }
  const sendReview = async (event: React.FormEvent) => { event.preventDefault(); if (!place) return; try { const r = await visitorRequest(`/api/v1/tourism/places/${place.id}/reviews`, { method: 'POST', body: JSON.stringify({ content: review }) }); if (!r.ok) throw new Error(); setReview(''); setMessage(t.pending) } catch { setMessage(language === 'ne' ? 'समीक्षा पठाउन सकिएन।' : 'Review could not be submitted.') } }
  const report = async (reviewId: string) => { const reasons = ['SPAM', 'ABUSIVE_CONTENT', 'FALSE_INFORMATION', 'PERSONAL_INFORMATION', 'OTHER']; const reason = window.prompt(language === 'ne' ? `कारण छान्नुहोस्: ${reasons.join(', ')}` : `Choose a reason: ${reasons.join(', ')}`, 'OTHER'); if (!reason) return; try { const response = await visitorRequest(`/api/v1/tourism/reviews/${reviewId}/report`, { method: 'POST', body: JSON.stringify({ reason: reason.toUpperCase() }) }); if (!response.ok) throw new Error(); setMessage(t.reported) } catch { setMessage(language === 'ne' ? 'रिपोर्ट पठाउन सकिएन।' : 'Report could not be submitted.') } }
  if (!place) return <main className="tourism-page"><TourismHeader /><div className="tourism-detail-empty">{error ? t.error : '…'} <a href="/tourism">{t.back}</a></div><TourismFooter /></main>
  const name = language === 'ne' ? place.nameNp : place.nameEn || place.nameNp
  const sections = [[t.about, local(place.descriptionNp, place.descriptionEn)], [t.history, local(place.historyNp, place.historyEn)], [t.culture, local(place.culturalSignificanceNp, place.culturalSignificanceEn)], [t.religion, local(place.religiousSignificanceNp, place.religiousSignificanceEn)], [t.nature, local(place.naturalFeaturesNp, place.naturalFeaturesEn)], [t.activities, local(place.activitiesNp, place.activitiesEn)], [t.bestTime, local(place.bestTimeNp, place.bestTimeEn)], [t.directions, local(place.howToReachNp, place.howToReachEn)], [t.facilities, local(place.facilitiesNp, place.facilitiesEn)], [t.safety, local(place.safetyInfoNp, place.safetyInfoEn)]].filter(([, content]) => content !== t.unavailableInfo)
  const directionsUrl = place.latitude != null && place.longitude != null ? `/map?destination=${encodeURIComponent(place.slug)}` : '/map'
  return <main className="tourism-page"><TourismHeader /><div className="tourism-detail-wrap"><div className="tourism-breadcrumb"><a href="/">{language === 'ne' ? 'गृहपृष्ठ' : 'Home'}</a> / <a href="/tourism">{t.back}</a> / {name}</div>
    <section className="tourism-detail-hero"><div><span className="tourism-category-inline">{place.category.icon} {language === 'ne' ? place.category.nameNp : place.category.nameEn}</span><h1>{name}</h1><div className="tourism-detail-meta"><span>⌖ {t.ward} {place.wardNumber ?? '—'}</span><span>★ {Number(place.averageRating).toFixed(1)} ({place.ratingCount})</span><span>◉ {place.viewCount.toLocaleString()} {t.views}</span></div></div><button className="tourism-save" onClick={async () => { try { const r = await visitorRequest(`/api/v1/tourism/places/${place.id}/favorite`, { method: 'POST' }); if (r.ok) setSaved((await r.json() as { saved: boolean }).saved) } catch { setMessage('Could not save favorite.') } }}>{saved ? `♥ ${t.saved}` : `♡ ${t.save}`}</button></section>
    {images.length > 0 ? <section className="tourism-gallery">{images.slice(0, 5).map((image, index) => <button className={`tourism-gallery-image tourism-gallery-${index}`} key={image.id} onClick={() => setViewer(index)}><img src={image.url} alt={image.altText || name} loading={index > 1 ? 'lazy' : 'eager'} />{index === 4 && images.length > 5 && <span>+{images.length - 5}</span>}</button>)}</section> : <div className="tourism-no-gallery">{t.photosMissing}</div>}
    <div className="tourism-detail-columns"><div>{sections.map(([title, content]) => <section className="tourism-detail-section" key={String(title)}><h2>{title}</h2><p>{content}</p></section>)}{!place.historyNp && !place.historyEn && <section className="tourism-detail-section"><h2>{t.history}</h2><p>{language === 'ne' ? 'यस स्थानको विस्तृत ऐतिहासिक विवरण हाल उपलब्ध छैन।' : 'Detailed historical information about this place is not currently available.'}</p></section>}<section className="tourism-review-area"><h2>{t.rate}</h2><div className="tourism-stars" role="radiogroup" aria-label={t.rate}>{[1, 2, 3, 4, 5].map((n) => <button key={n} role="radio" aria-checked={rating === n} aria-label={`${n} stars`} onClick={() => rate(n)}>{rating >= n ? '★' : '☆'}</button>)}</div><form onSubmit={sendReview}><label>{t.write}<textarea minLength={10} maxLength={2000} value={review} onChange={(e) => setReview(e.target.value)} required /></label><button disabled={review.trim().length < 10}>{t.send}</button></form>{message && <p role="status">{message}</p>}<h2>{t.reviews}</h2>{place.tourismReviews?.length ? place.tourismReviews.map((item) => <blockquote key={item.id}>{item.content}<button className="tourism-report-button" onClick={() => void report(item.id)}>{t.report}</button></blockquote>) : <p>{t.noReviews}</p>}</section></div><aside className="tourism-detail-aside"><div><h2>{t.map}</h2>{place.latitude != null && place.longitude != null ? <><div className="tourism-coordinate-map"><iframe title={`${name} map`} loading="lazy" src={`https://www.openstreetmap.org/export/embed.html?marker=${place.latitude}%2C${place.longitude}&layer=mapnik`} /><small>© OpenStreetMap contributors</small></div><a className="tourism-direction-link" href={directionsUrl}>{t.directions} ↗</a></> : <p>{t.unavailableInfo}</p>}<p className="tourism-street-view">{t.street}</p></div></aside></div>
    </div>{viewer !== null && <div className="tourism-lightbox" role="dialog" aria-modal="true" onClick={() => setViewer(null)}><button aria-label="Close" onClick={() => setViewer(null)}>×</button><button aria-label="Previous" onClick={(event) => { event.stopPropagation(); setViewer((viewer - 1 + images.length) % images.length) }}>‹</button><figure onClick={(event) => event.stopPropagation()}><img src={images[viewer].url} alt={images[viewer].altText || name} /><figcaption>{images[viewer].captionNp || images[viewer].captionEn || `${viewer + 1} / ${images.length}`}</figcaption></figure><button aria-label="Next" onClick={(event) => { event.stopPropagation(); setViewer((viewer + 1) % images.length) }}>›</button></div>}<TourismFooter /></main>
}
